### ISSUE TITLE
Trigger SDK docs rebuild automatically

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit.network#29]
Closes https://github.com/comit-network/comit.network/issues/7

Right now, the build process is not yet automated. Ideally, Github will trigger the `npm run build:sdk` command whenever there is a new release of the `comit-js-sdk` repo and update the website.

## Build Workflow

In the meantime, if you need to update the API docs, here's how you can do it.

```
.
├──work/
|   ├── comit-js-sdk/
|   └── comit.network/
```

- First, make sure that you have both `comit-js-sdk` and `comit.network` repos on your machine, within the same directory (see above.) 
- Do a `git pull` to make sure both repos are up-to-date.
- `cd comit.network/` and run `npm run build:sdk`. This will generate `comit-js-sdk` documentation and update the website source in a single step.
- Open the website locally with `npm run start` to make sure there are no syntax errors.
- `git add .` `git commit` to commit the updated source files.
- `git push` to `master` rebuild the live website.

## Workflow Definition

- The above steps can be defined as a [Github action](https://github.com/features/actions) which is **triggered whenever a new SDK release is created**.

- When the action is triggered the workflow should **Open a new PR containing the commit.**

- The workflow should live in the `comit.network` repo, and be triggered by a `release` event from the `comit-js-sdk` repo. The workflow will `git clone comit-js-sdk` and run the `npm run build:sdk` command.

Note: You can use the `repo_dispatch` github feature, see how it is done in coblox/admin for the label sync.
Note: OR you can do the git commit and push on comit.network from comit-js-sdk github action.
Note: Be aware of release automation for SDK #181

**Comment by D4nte** [comment]
@D4nte to create a new issue first about handling multiple versions of the SDK in the documentation website.

**Comment by bonomat** [comment]
@D4nte : last comment says you are in charge of creating new issues for handling multiple versions of the SDK first. What's the status of this please?

**Comment by D4nte** [comment]
> @D4nte : last comment says you are in charge of creating new issues for handling multiple versions of the SDK first. What's the status of this please?

https://github.com/comit-network/comit.network/issues/46

**Comment by yosriady** [comment]
Updated workflow definition.
