### ISSUE TITLE
Redirect old blog to new blog

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit.network#32]
## Problem

We want the URL of the old blog (https://blog.coblox.tech) to redirect users to the new one (https://comit.network/blog). 

Ideally, we want to redirect `https://blog.coblox.tech/2020/01/31/january-dev-update.html` to `https://comit.network/blog/2020/01/31/january-dev-update`. However, this is actually **impossible** with pure DNS because DNS has no knowledge of HTTP paths.

## Solution 1

If possible, add a 301 URL Redirect record from `blog.coblox.tech` to `comit.network/blog` on the DNS dashboard.

## Solution 2

If the dashboard doesn't provide the 301 Redirect rule, we'll need to do [this](https://aws.amazon.com/premiumsupport/knowledge-center/redirect-domain-route-53/) [approach](https://stackoverflow.com/questions/9444055/using-dns-to-redirect-to-another-url-with-a-path) to achieve the same thing (except the rest of the URL paths are removed.) 

It's a complicated multi-step process, summarized here:

- In the Route 53 console, make sure the hosted zone named `blog.coblox.tech` exists.
- In S3, create an empty bucket `blog.coblox.tech`
- Select the bucket you just created, and then choose Properties. Expand the Static Website Hosting drop-down menu, and then choose Redirect all requests to another host name.
- In the Redirect all requests to another host name field, enter `comit.network/blog` and save.
- In the Route 53 console, select the hosted zone named `blog.coblox.tech`
- In Route53, create an A record for `blog.coblox.tech` with the following values:

```
Record Type: Choose A – IPv4 address.
Alias: Choose Yes.
Alias Target: Select the blank value field, expand the drop-down menu, and then choose your S3 bucket `blog.coblox.tech` under the heading S3 Website Endpoints.
Routing Policy: Choose Simple.
Evaluate Health Target: Choose No, and then choose Create.
```

> Make sure that the alias target above is set to the `blog.coblox.tech` bucket

You can confirm it works by browsing to `blog.coblox.tech` or CURL to `blog.coblox.tech`. You should see "301 Moved Permanently" in your curl output, redirecting to `comit.network/blog`.

**Comment by yosriady** [comment]
@da-kami

**Comment by alvinjiang** [comment]
done, please test

**Comment by yosriady** [comment]
@alvinjiang 

CNAME does not work as a redirect, we want to use Namecheap's URL Redirect  record.
More details why: https://www.namecheap.com/support/knowledgebase/article.aspx/9604/2237/types-of-domain-redirects--301-302-url-redirects-url-frame-and-cname

You can follow these instructions: https://www.namecheap.com/support/knowledgebase/article.aspx/385/2237/how-to-redirect-a-url-for-a-domain

**Comment by alvinjiang** [comment]
that's what i did, Yos - perhaps you could test it?

**Comment by yosriady** [comment]
So the currently configured Namecheap redirect should work - I've tested with other domains and this works fine (try going to `comit.yos.io`):

<img width="793" alt="Screenshot 2020-02-26 at 3 02 17 PM" src="https://user-images.githubusercontent.com/1084226/75320186-231c5c80-58a9-11ea-8f06-9ceabf7a165d.png">

However, `blog.coblox.tech` does not. 

@da-kami Do you know where the old blog was hosted? It's possible that there are other settings on the host provider that are conflicting with what we have.

**Comment by yosriady** [comment]
I've checked with Martijn and it's not under the Netlify TenX org.

**Comment by bonomat** [comment]
It's hosted on github pages: https://github.com/tenx-tech/coblox.tech

**Comment by bonomat** [comment]
sorry, wrong, the blog is hosted here: https://github.com/coblox/blog

**Comment by bonomat** [comment]
Don't spend too much time on it. Maybe easiest is let 
http://blog.coblox.tech redirect to http://comit.network

from there one can find its way to the blog.

**Comment by yosriady** [comment]
@da-kami I think this CNAME Github domain config might be interfering with the domain redirects, could you remove it and check if it works? https://github.com/coblox/blog/blob/master/CNAME

I would like to focus on the app and not spend too much time on this, so would be great if someone takes over this. If you need more context, everything's on this thread.

**Comment by bonomat** [comment]
@yosriady : I removed the cname file and disabled github pages for the github.com/coblox/blog

**Comment by da-kami** [comment]
@bonomat have you also adapted the domain settings like @yosriady suggested? 
Accessing blog.coblox.tech still results in loading forever. 
I feel we should EITHER bring the old blog back and leave it for another while with a "we moved" post; OR get the re-direct working. The current state is not optimal.

**Comment by bonomat** [comment]
@da-kami : I just removed the cname file and disabled github pages. 
Now we just need to redirect the domain via dns settings.

**Comment by yosriady** [comment]
http://blog.coblox.tech/ -> works fine
https://blog.coblox.tech/ -> does not work

If either of you would like to debug why, feel free. 
Otherwise, we can return the old blog as @da-kami suggested.

**Comment by da-kami** [comment]
Decision: We don't invest time and ignore this for now. Once the new homepage start-page is launched we redirect from blog.coblox.tech to comit.network
