### ISSUE TITLE
Follow up with documentation

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit.network#33]
@yosriady please feel free to add to this if there already is something on your radar.

Note: This ticket is also a reminder that the documentation does not just stop at the current tickets we have, but should be constantly maintained.
I put several questions at the bottom. 

## Problem

I was just going through the product-squad wiki and noticed this comment at the end:
( ref: https://github.com/coblox/product-squad/wiki/COMIT-Product-Technical-Specification#feedback)

```
In particular:
* An explanation of the Order message schema.
* An explanation of the steps of the COMIT protocol.
```

This is only partly done in the current documentation and should be extended.

## Goal

A more useful and elaborate documentation.

## Proposed Solution

Immediate actions:

* Extend the "COMIT Protocol" Section (or should this be somewhere else? 
    * Add a graphic that explains the relation between cnd <> comit-js-sdk <> create-comit-app. Include taker and maker as actors so it is clear what the different tools bring to the table.

Clarification needed:

* Documentation for `Order` (or `Negotiation` in total...)
    * Should we actually have an example for the Order message schema? 
    * The whole negotiation is basically still in the a trial/example state. Are we planning to change this at some point? 
    * Is more documentation needed at the moment?

**Comment by yosriady** [comment]
Yes, I'm all for it. If there's no documentation of it, it doesn't exist.

**Comment by yosriady** [comment]
I think we can discuss some of the points here https://github.com/comit-network/app/issues/7 during the meeting
