### ISSUE TITLE
Overview page that points to `/docs`

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit.network#45]
## Problem

When navigating to `/docs` on the homepage there is nothing there. (no page, 404)

## Goal

Not have 404 but an entry point to the documentation.

## Recommendation

Redirect to https://comit.network/docs/getting-started/create-comit-app/

Consider a generic solution that would allow to fix this issue for any url and redirect to the best existing page.
Example: https://comit.network/docs/getting-started/-> https://comit.network/docs/getting-started/create-comit-app

**Comment by yosriady** [comment]
This might only be solvable by the Docusaurus team https://v2.docusaurus.io/feedback/p/home-page-for-docs

**Comment by yosriady** [comment]
They've started to work on it https://github.com/facebook/docusaurus/issues/2507

**Comment by yosriady** [comment]
Feature now available on `v2.0.0-alpha.55`
