### ISSUE TITLE
Better document what `comit-scripts` does

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit.network#48]
## Problem

There is no clear explanation of what `comit-scripts` does.

## Goal

Ensure that users and developers are aware of what they need to run and what `comit-scripts` does for them. It should be clear that they do not need to start their own nodes or worry about funding. It should also be clear on how `comit-scripts` forward information to the apps (via the env file).

Reasoning why some decision were made would also be interesting to allow the dev to better grasp the point of this tool.

## Recommendation

A documentation that explains what `comit-scripts` gives you and how a developer is expected to interact with it, and what it does not give you (testnet/mainnet).

Should go under the `Getting Started` section.

**Comment by da-kami** [comment]
Note that this ticket will be tackled with with https://github.com/comit-network/comit.network/pull/56 if decide to merge it :)
