### ISSUE TITLE
Document COMIT App dev journey through the documentation

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit.network#49]
## Problem

As highlighted by @yosriady in https://github.com/comit-network/comit.network/issues/42#issuecomment-600958770. A developer will go through the documentation is the way we present it to them and/or the way they feel they need to know.

Currently, we have a vague idea of this journey but it not explicitly stated.

## Goal

The goal is to explicitly state the journey so that:
- We can review and validate it and confirm it makes sense
- Ensure that what we do is aligned with the target journey
- Better guide a developer so they know when they need to expect such and such information, allowing them to skip forward if they want to

## Recommendation

Ensure that the left sidebar matches the journey even if it means having some empty sections for now.

### Journey proposal

Can be discussed as part of the review process.

1. Arrives at the start-page of comit.network
1. Read about what COMIT does (short overview)
1. Read Getting Started section to run an example.
1. Read create own app Tutorial
1. Sets up with comit-scripts (Developers have no knowledge of infra just yet). A general overview would be helpful here, but perhaps it makes more sense later on.
1. Read Core Concepts and Protocol explanation
1. Finished going through create own app tutorial
1. Developer is now ready to deploy their COMIT app on testnet.
1. Infra Overview would be most useful here, when deploying the app as want devto stop using comit-scripts. So maybe time to explain what comit-scripts does it details at a way to explain what is needed.
1.Developer has gone live with the COMIT App on testnet / mainnet

### Sections

``` 
    Getting Started
        Run an example app # Current `create-comit-app` get started
        Dev Environment Setup # Short overview of comit-scripts
        Write your first app
        Deploy in testnet # infrastructure overview + what needs to happen to go testnet
    COMIT Protocol
        COMIT protocol stack
        COMIT projects
        Core Concepts
            Atomic Swaps using HTLCs
            (...)
    COMIT JavaScript SDK
```

### Actions to take

- Rename "Create-comit-app to "Run an example app"
- Pull comit-scripts setup description out of the current "Create-comit-app" section into "Dev Environment Setup".
- Move "Core Concepts" under "COMIT Protocol"
- Rename "Javascript" to "JavaScript"

**Comment by yosriady** [comment]
> At this stage I am not certain about the best format but I see 2 ways:
>
> 1. The journey is the left-hand navigation bar. We Update it to create specific (empty) topic to ensure that it all makes sense
> 2. A table of content kind of intro that links and summarise each section.

I think having shorter bite-sized pages with approach (1) would work well. We can use subsections of the sidebar as a table of contents. Splitting it up to shorter pages can help keep developers' attention spans. 

Otherwise, going with approach (2) might result in very long pages that you have to keep scrolling for to find what you need, which might seem overwhelming to beginners.

**Comment by da-kami** [comment]
Closing this because besides #42 all of the bullet points are done once https://github.com/comit-network/comit.network/pull/57 merges. 

And since #42 is tracked I don't think we need this issue.
