### ISSUE TITLE
Register a CoBlox Netlify team

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit.network#58]
Right now the `comit.network` site is hosted under the TenX org. It's cheaper with just 2 members, but adding more members needs is a big hassle and goes through a lot of people.

Moving forward, we should sign up to our own Netlify Pro account https://www.netlify.com/pricing/ for easier collaboration.

**Comment by yosriady** [comment]
@bonomat Could we sign up for our own CoBlox Netlify account? This will:

- Give us more control over domain and site configuration.
- Make it much faster to add collaborators.

**Comment by bonomat** [comment]
Yes, sure.
