### ISSUE TITLE
Intro section for the comit-js-sdk

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit.network#6]
The generation tool of choice is Typedoc, it uses the README as the home page so we can update the README for this issue.

**Comment by D4nte** [comment]
@da-kami please note the update.

**Comment by da-kami** [comment]
Using the README is good enough for the moment. If we ever feel we need more/something else we can change it later.

**Comment by da-kami** [comment]
@D4nte I am currently working on the READMEs of all projects, and I would like to add a header to all READMEs in all projects that shows a short overview of what COMIT is about and what the specific repository is. I think it helps greatly when developers check our repositories on Github.
Examples: https://github.com/comit-network/comit-rs/blob/update-readme/README.md

But this would mean that when integrating the SDK's README as start page there would be the header included as well. Do you think that is a problem?
If this is not good for the docu we have 2 possibilities:
1. I don't include the header in the SDK's readme
2. We don't use the README for intro in the docu.

Thoughts?

**Comment by D4nte** [comment]
> @D4nte I am currently working on the READMEs of all projects, and I would like to add a header to all READMEs in all projects that shows a short overview of what COMIT is about and what the specific repository is. I think it helps greatly when developers check our repositories on Github.
> Example: [comit-network/comit-rs:README.md@`update-readme`](https://github.com/comit-network/comit-rs/blob/update-readme/README.md) [](/comit-network/comit-rs/blob/HEAD@{2020-02-07T05:13:29Z}/README.md)
> 
> But this would mean that when integrating the SDK's README as start page there would be the header included as well. Do you think that is a problem?
> If this is not good for the docu we have 2 possibilities:
> 
>     1. I don't include the header in the SDK's readme
> 
>     2. We don't use the README for intro in the docu.
> 
> 
> Thoughts?

I think that's fine.
