### ISSUE TITLE
Release process and generated documentation integration

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit.network#7]
Decisions to make: 

* When and how should Docusaurus be triggered to deploy a new version of the homepage (including documentation) 
    * I don't have a clear solution on that in my head yet. the build pipeline(s) may be a result of this.

Proposal:

We will have to distinguish scenarios where we release a new homepage version upon changing hand-written documentation or generated documentation. For hand written documentation there will be a PR (created after changing/adding files).

The documentation for the comit-js-sdk should be generated and released upon release a new SDK version. The SDK release process should automatically trigger the creation of a PR in the documentation repository. This https://github.com/coblox/admin/issues/182#issuecomment-575003774 by @yosriady adds some more details on how to achieve the integration and release of generated documentation parts.

The webpage (including the documentation) is released upon merging a PR.

**Comment by D4nte** [comment]
@yosriady / @da-kami is it still needed?

**Comment by yosriady** [comment]
Yes, but it's now tracked by https://github.com/comit-network/comit.network/issues/29
